name: CI - Docs
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: testthedocs/github-pages-deploy-action@master
      env:
        BUILD_DIR: / # The folder, the action should deploy.
        BUILD_SCRIPT: npm install && npm run-script build
